version: "3.8"

services:
  accounts:
    image: soukupandrej/accounts:latest
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - soukupandrej-network

  loans:
    image: soukupandrej/loans:latest
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - soukupandrej-network

  cards:
    image: soukupandrej/cards:latest
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - soukupandrej-network

networks:
  soukupandrej-network:
