version: "3.8"

services:
  configserver:
    image: soukupandrej/configserver:latest
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - soukupandrej-network

  accounts:
    image: soukupandrej/accounts:latest
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - soukupandrej-network
    depends_on:
      - configserver
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


  loans:
    image: soukupandrej/loans:latest
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - soukupandrej-network
    depends_on:
      - configserver
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: soukupandrej/cards:latest
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - soukupandrej-network
    depends_on:
      - configserver
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  soukupandrej-network:
